"""
爬虫模块，包含各个数据源的爬虫实现
"""

from .base_crawler import BaseCrawler
from .json_crawler import JSONCrawler
from .actual_load_crawler import ActualLoadCrawler
from .day_ahead_load_crawler import DayAheadLoadCrawler
from .week_ahead_load_crawler import WeekAheadLoadCrawler
from .system_backup_crawler import SystemBackupCrawler
from .total_generation_forecast_crawler import TotalGenerationForecastCrawler
from .external_power_plan_crawler import ExternalPowerPlanCrawler
from .non_market_solar_forecast_crawler import NonMarketSolarForecastCrawler
from .non_market_wind_forecast_crawler import NonMarketWindForecastCrawler
from .non_market_nuclear_forecast_crawler import NonMarketNuclearForecastCrawler
from .non_market_hydro_forecast_crawler import NonMarketHydroForecastCrawler
from .day_ahead_solar_total_forecast_crawler import DayAheadSolarTotalForecastCrawler
from .day_ahead_wind_total_forecast_crawler import DayAheadWindTotalForecastCrawler
from .week_ahead_pumped_storage_forecast_crawler import WeekAheadPumpedStorageForecastCrawler
from .day_ahead_hydro_total_forecast_crawler import DayAheadHydroTotalForecastCrawler
from .day_ahead_pumped_storage_forecast_crawler import DayAheadPumpedStorageForecastCrawler
from .actual_total_generation_crawler import ActualTotalGenerationCrawler
from .actual_solar_output_crawler import ActualSolarOutputCrawler
from .actual_wind_output_crawler import ActualWindOutputCrawler
from .actual_hydro_output_crawler import ActualHydroOutputCrawler
from .actual_pumped_storage_output_crawler import ActualPumpedStorageOutputCrawler
from .non_market_total_output_crawler import NonMarketTotalOutputCrawler
from .non_market_solar_output_crawler import NonMarketSolarOutputCrawler 
from .non_market_wind_output_crawler import NonMarketWindOutputCrawler 
from .non_market_nuclear_output_crawler import NonMarketNuclearOutputCrawler 
from .non_market_hydro_output_crawler import NonMarketHydroOutputCrawler 
from .day_ahead_price_crawler import DayAheadPriceCrawler 