name: xgboost
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - xgboost
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn
      - mlflow
      - SQLAlchemy
      - mysql-connector-python
